// 오프라인 이모지 검색용 큐레이션 목록 (char + 검색 키워드).
// 외부 요청 없이 로컬에서 `:` 검색에 사용.
export interface EmojiItem {
    char: string;
    names: string[];
}

// [문자, "키워드 나열(영문+일부 한글)"] 튜플 → EmojiItem
const RAW: [string, string][] = [
    // 표정
    ["😀", "grin smile happy 웃음 미소"],
    ["😁", "beam grin happy smile 웃음"],
    ["😂", "joy lol laugh tears 웃음 눈물"],
    ["🤣", "rofl laugh rolling 폭소"],
    ["😊", "blush smile happy 미소 방긋"],
    ["🙂", "slight smile 미소"],
    ["😉", "wink 윙크"],
    ["😍", "love heart eyes 하트 사랑"],
    ["🥰", "love hearts 사랑 애정"],
    ["😘", "kiss 뽀뽀 키스"],
    ["😎", "cool sunglasses 선글라스 멋짐"],
    ["🤩", "star struck wow 반짝 감탄"],
    ["🤔", "think thinking 고민 생각"],
    ["🙃", "upside down 뒤집힘"],
    ["😐", "neutral 무표정"],
    ["😴", "sleep zzz 잠 졸림"],
    ["😭", "cry sob tears 울음 눈물"],
    ["😅", "sweat nervous 식은땀"],
    ["😳", "flushed shock 당황"],
    ["🥲", "smile tear 눈물 미소"],
    ["😇", "angel innocent 천사"],
    ["🤗", "hug 포옹 안기"],
    ["🤯", "mind blown explode 놀람 충격"],
    ["😱", "scream shock 비명 충격"],
    ["😡", "angry mad rage 화남 분노"],
    ["🥳", "party celebrate 파티 축하"],
    ["😜", "wink tongue 메롱 장난"],
    ["🤪", "crazy zany 광기 장난"],
    ["😌", "relieved calm 안도 편안"],
    ["🙄", "eye roll 눈흘김"],
    // 손동작/사람
    ["👍", "thumbs up good like 좋아요 최고"],
    ["👎", "thumbs down bad 싫어요"],
    ["👏", "clap applause 박수"],
    ["🙌", "raise hands celebrate 만세"],
    ["🙏", "pray thanks please 기도 부탁 감사"],
    ["👌", "ok perfect 오케이"],
    ["✌️", "victory peace 브이 평화"],
    ["🤞", "fingers crossed 행운"],
    ["💪", "muscle strong 근육 힘"],
    ["👋", "wave hi hello bye 인사 안녕"],
    ["🤝", "handshake deal 악수 협력"],
    ["👀", "eyes look 눈 보기"],
    ["🧠", "brain smart 뇌 지능"],
    ["🫶", "heart hands love 하트손 사랑"],
    ["🤙", "call hang loose 전화"],
    // 하트/기호
    ["❤️", "heart red love 하트 사랑"],
    ["🧡", "orange heart 주황 하트"],
    ["💛", "yellow heart 노랑 하트"],
    ["💚", "green heart 초록 하트"],
    ["💙", "blue heart 파랑 하트"],
    ["💜", "purple heart 보라 하트"],
    ["🖤", "black heart 검정 하트"],
    ["🤍", "white heart 흰 하트"],
    ["💖", "sparkle heart 반짝 하트"],
    ["💕", "two hearts 하트 사랑"],
    ["💔", "broken heart 이별 상심"],
    ["✨", "sparkles shine 반짝 반짝임"],
    ["⭐", "star 별"],
    ["🌟", "glowing star 별 반짝"],
    ["🔥", "fire hot lit 불 인기"],
    ["💯", "hundred perfect 백점 최고"],
    ["✅", "check done ok 체크 완료"],
    ["❌", "cross x no 엑스 취소"],
    ["⚠️", "warning caution 경고 주의"],
    ["❓", "question 물음표"],
    ["❗", "exclamation 느낌표"],
    ["💡", "idea bulb light 아이디어 전구"],
    ["🎯", "target goal dart 목표 과녁"],
    ["🏆", "trophy win award 트로피 우승"],
    ["🥇", "gold medal first 금메달 1등"],
    ["🎉", "party tada celebrate 축하 파티"],
    ["🎊", "confetti celebrate 축하"],
    ["🎁", "gift present 선물"],
    ["🔔", "bell notify 알림 종"],
    ["📌", "pin 핀 고정"],
    ["📍", "location pin place 위치 장소"],
    ["🗓️", "calendar date 달력 날짜"],
    ["📅", "calendar date 달력 날짜"],
    ["⏰", "alarm clock time 알람 시간"],
    ["⌛", "hourglass time 모래시계 시간"],
    // 차트/업무
    ["📊", "bar chart graph 막대 그래프 차트"],
    ["📈", "chart up growth 상승 성장 그래프"],
    ["📉", "chart down decline 하락 그래프"],
    ["💰", "money bag cash 돈 자금"],
    ["💵", "dollar money 달러 돈"],
    ["💳", "card payment 카드 결제"],
    ["🏦", "bank 은행"],
    ["💻", "laptop computer 노트북 컴퓨터"],
    ["🖥️", "desktop computer 데스크탑"],
    ["📱", "phone mobile 휴대폰 모바일"],
    ["⌨️", "keyboard 키보드"],
    ["🖱️", "mouse 마우스"],
    ["💾", "save disk 저장 디스크"],
    ["📁", "folder 폴더"],
    ["📂", "open folder 폴더"],
    ["📄", "document file page 문서 파일"],
    ["📝", "memo note write 메모 작성"],
    ["✏️", "pencil write 연필"],
    ["🖊️", "pen write 펜"],
    ["📎", "paperclip clip 클립 첨부"],
    ["🔗", "link chain 링크 연결"],
    ["🔒", "lock secure 잠금 보안"],
    ["🔓", "unlock 잠금해제"],
    ["🔑", "key 열쇠"],
    ["🔍", "search magnify 검색 돋보기"],
    ["📢", "announce megaphone 공지 확성기"],
    ["📣", "cheer megaphone 응원"],
    ["🚀", "rocket launch fast 로켓 출시 빠름"],
    ["⚡", "bolt fast power 번개 빠름 전기"],
    ["🔋", "battery 배터리"],
    ["🔌", "plug power 플러그 전원"],
    ["🛠️", "tools fix 도구 수리"],
    ["⚙️", "gear settings 설정 톱니"],
    ["🧩", "puzzle piece 퍼즐 조각"],
    ["📦", "package box 상자 택배"],
    ["🛒", "cart shopping 장바구니"],
    ["🏷️", "tag label price 태그 라벨"],
    // 자연/날씨
    ["☀️", "sun sunny 해 맑음"],
    ["🌤️", "sun cloud 구름 해"],
    ["☁️", "cloud 구름"],
    ["🌧️", "rain 비"],
    ["⛈️", "storm thunder 폭풍 천둥"],
    ["❄️", "snow cold 눈 추위"],
    ["🌈", "rainbow 무지개"],
    ["🌙", "moon night 달 밤"],
    ["🌍", "earth world globe 지구 세계"],
    ["🌱", "seedling grow plant 새싹 성장"],
    ["🌳", "tree 나무"],
    ["🌸", "blossom flower 벚꽃 꽃"],
    ["🌺", "flower 꽃"],
    ["🍀", "clover luck 클로버 행운"],
    ["🔆", "bright light 밝음"],
    // 동물
    ["🐶", "dog puppy 강아지 개"],
    ["🐱", "cat 고양이"],
    ["🐰", "rabbit bunny 토끼"],
    ["🦊", "fox 여우"],
    ["🐻", "bear 곰"],
    ["🐼", "panda 판다"],
    ["🐯", "tiger 호랑이"],
    ["🦁", "lion 사자"],
    ["🐢", "turtle 거북이"],
    ["🐝", "bee 벌"],
    ["🦋", "butterfly 나비"],
    ["🐧", "penguin 펭귄"],
    ["🐦", "bird 새"],
    ["🐟", "fish 물고기"],
    ["🦄", "unicorn 유니콘"],
    // 음식
    ["🍎", "apple 사과"],
    ["🍌", "banana 바나나"],
    ["🍓", "strawberry 딸기"],
    ["🍉", "watermelon 수박"],
    ["🍇", "grape 포도"],
    ["🍑", "peach 복숭아"],
    ["🍔", "burger 햄버거"],
    ["🍕", "pizza 피자"],
    ["🍜", "noodle ramen 라면 국수"],
    ["🍣", "sushi 초밥"],
    ["🍚", "rice 밥"],
    ["🍗", "chicken meat 치킨 고기"],
    ["🍰", "cake dessert 케이크 디저트"],
    ["🍪", "cookie 쿠키"],
    ["🍫", "chocolate 초콜릿"],
    ["☕", "coffee cafe 커피 카페"],
    ["🍵", "tea 차"],
    ["🍺", "beer 맥주"],
    ["🍷", "wine 와인"],
    ["🥤", "drink soda 음료"],
    // 이동/장소
    ["🚗", "car 자동차"],
    ["🚕", "taxi 택시"],
    ["🚙", "suv car 차"],
    ["🚌", "bus 버스"],
    ["🚄", "train 기차"],
    ["✈️", "plane flight travel 비행기 여행"],
    ["🚲", "bike bicycle 자전거"],
    ["🛵", "scooter 스쿠터"],
    ["🚢", "ship boat 배"],
    ["🏠", "house home 집"],
    ["🏢", "office building 회사 빌딩"],
    ["🏫", "school 학교"],
    ["🏥", "hospital 병원"],
    ["🏦", "bank 은행 건물"],
    ["🔌", "charge ev 충전"],
    ["⛽", "gas fuel station 주유소 연료"],
    // 기타 자주 쓰는 것
    ["👑", "crown king best 왕관 최고"],
    ["💎", "diamond gem 다이아 보석"],
    ["🎨", "art palette design 그림 디자인"],
    ["🎵", "music note 음악"],
    ["📚", "books study 책 공부"],
    ["🧾", "receipt bill 영수증"],
    ["🩺", "health medical 건강 의료"],
    ["🧪", "test lab science 실험 과학"],
    ["🔬", "microscope science 현미경 과학"],
    ["💊", "pill medicine 약"],
    ["🧭", "compass direction 나침반 방향"],
    ["🗺️", "map 지도"],
    ["🏁", "flag finish 결승 깃발"],
    ["🎮", "game controller 게임"],
    ["📺", "tv 티비"],
    ["🎬", "movie film 영화"],
    ["📷", "camera photo 카메라 사진"],
    ["🔦", "flashlight 손전등"],
];

export const EMOJIS: EmojiItem[] = RAW.map(([char, k]) => ({ char, names: k.split(/\s+/) }));

// 검색: 쿼리가 비면 인기 이모지, 있으면 이름에 포함된 것.
export function searchEmojis(query: string, limit = 40): EmojiItem[] {
    const q = query.trim().toLowerCase();
    if (!q) return EMOJIS.slice(0, limit);
    const starts: EmojiItem[] = [];
    const includes: EmojiItem[] = [];
    for (const e of EMOJIS) {
        if (e.names.some((n) => n.startsWith(q))) starts.push(e);
        else if (e.names.some((n) => n.includes(q))) includes.push(e);
    }
    return [...starts, ...includes].slice(0, limit);
}
