export const peopleEmojis = [
    { emoji: "😀", label: "grinning" },
    { emoji: "😃", label: "smile" },
    { emoji: "😄", label: "smile" },
    { emoji: "😁", label: "grin" },
    { emoji: "😆", label: "laugh" },
    { emoji: "😅", label: "sweat_smile" },
    { emoji: "😂", label: "joy" },
    { emoji: "😊", label: "blush" },
    { emoji: "😇", label: "innocent" },
    { emoji: "🙂", label: "slight_smile" },
    { emoji: "🙃", label: "upside_down" },
    { emoji: "😉", label: "wink" },
    { emoji: "😍", label: "heart_eyes" },
    { emoji: "🥰", label: "smiling_hearts" },
    { emoji: "😘", label: "kissing_heart" },
    { emoji: "😗", label: "kissing" },
    { emoji: "😙", label: "kissing_smiling_eyes" },
    { emoji: "😚", label: "kissing_closed_eyes" },
    { emoji: "😋", label: "yum" },
    { emoji: "😜", label: "stuck_out_tongue_wink" },
    { emoji: "🤪", label: "zany" },
    { emoji: "🤨", label: "raised_eyebrow" },
    { emoji: "🧐", label: "monocle" },
    { emoji: "🤓", label: "nerd" },
    { emoji: "😎", label: "sunglasses" },
    { emoji: "🥸", label: "disguise" },
    { emoji: "🤩", label: "star_struck" },
    { emoji: "🥳", label: "party" },
    { emoji: "😏", label: "smirk" },
    { emoji: "😒", label: "unamused" },
    { emoji: "😞", label: "disappointed" },
    { emoji: "😔", label: "pensive" },
    { emoji: "😟", label: "worried" },
    { emoji: "😕", label: "confused" },
    { emoji: "🙁", label: "slightly_frowning" },
    { emoji: "☹️", label: "frowning" },
    { emoji: "😣", label: "persevere" },
    { emoji: "😖", label: "confounded" },
    { emoji: "😫", label: "tired" },
    { emoji: "😩", label: "weary" },
    { emoji: "🥺", label: "pleading" },
    { emoji: "😢", label: "cry" },
    { emoji: "😭", label: "sob" },
    { emoji: "😤", label: "triumph" },
    { emoji: "😠", label: "angry" },
    { emoji: "😡", label: "rage" },
    { emoji: "🤬", label: "cursing" },
    { emoji: "🤯", label: "exploding_head" },
    { emoji: "😳", label: "flushed" },
    { emoji: "🥵", label: "hot" },
    { emoji: "🥶", label: "cold" },
    { emoji: "😱", label: "scream" },
    { emoji: "😨", label: "fear" },
    { emoji: "😰", label: "anxious" },
    { emoji: "😥", label: "sad_but_relieved" },
    { emoji: "😓", label: "sweat" },
];

export const animalEmojis = [
    { emoji: "🐶", label: "dog" },
    { emoji: "🐱", label: "cat" },
    { emoji: "🐭", label: "mouse" },
    { emoji: "🐹", label: "hamster" },
    { emoji: "🐰", label: "rabbit" },
    { emoji: "🦊", label: "fox" },
    { emoji: "🐻", label: "bear" },
    { emoji: "🐼", label: "panda" },
    { emoji: "🐨", label: "koala" },
    { emoji: "🐯", label: "tiger" },
    { emoji: "🦁", label: "lion" },
    { emoji: "🐮", label: "cow" },
    { emoji: "🐷", label: "pig" },
    { emoji: "🐸", label: "frog" },
    { emoji: "🐵", label: "monkey" },
    { emoji: "🦄", label: "unicorn" },
    { emoji: "🐔", label: "chicken" },
    { emoji: "🐧", label: "penguin" },
    { emoji: "🐦", label: "bird" },
    { emoji: "🐤", label: "chick" },
    { emoji: "🐣", label: "hatching_chick" },
    { emoji: "🐥", label: "front_chick" },
    { emoji: "🦆", label: "duck" },
    { emoji: "🦅", label: "eagle" },
    { emoji: "🦉", label: "owl" },
    { emoji: "🦇", label: "bat" },
    { emoji: "🐺", label: "wolf" },
    { emoji: "🐗", label: "boar" },
    { emoji: "🐴", label: "horse" },
    { emoji: "🦓", label: "zebra" },
    { emoji: "🦍", label: "gorilla" },
    { emoji: "🦧", label: "orangutan" },
    { emoji: "🐘", label: "elephant" },
    { emoji: "🦛", label: "hippo" },
    { emoji: "🦏", label: "rhino" },
    { emoji: "🐪", label: "camel" },
    { emoji: "🐫", label: "two_hump_camel" },
    { emoji: "🦒", label: "giraffe" },
    { emoji: "🦘", label: "kangaroo" },
    { emoji: "🦥", label: "sloth" },
    { emoji: "🦦", label: "otter" },
    { emoji: "🦨", label: "skunk" },
    { emoji: "🦡", label: "badger" },
    // ... 더 많은 동물 이모지 추가 가능
];

export const foodEmojis = [
    { emoji: "🍏", label: "green_apple" },
    { emoji: "🍎", label: "red_apple" },
    { emoji: "🍐", label: "pear" },
    { emoji: "🍊", label: "tangerine" },
    { emoji: "🍋", label: "lemon" },
    { emoji: "🍌", label: "banana" },
    { emoji: "🍉", label: "watermelon" },
    { emoji: "🍇", label: "grapes" },
    { emoji: "🍓", label: "strawberry" },
    { emoji: "🫐", label: "blueberry" },
    { emoji: "🍈", label: "melon" },
    { emoji: "🍒", label: "cherries" },
    { emoji: "🍑", label: "peach" },
    { emoji: "🥭", label: "mango" },
    { emoji: "🍍", label: "pineapple" },
    { emoji: "🥥", label: "coconut" },
    { emoji: "🥝", label: "kiwi" },
    { emoji: "🍅", label: "tomato" },
    { emoji: "🍆", label: "eggplant" },
    { emoji: "🥑", label: "avocado" },
    { emoji: "🥦", label: "broccoli" },
    { emoji: "🥬", label: "leafy_green" },
    { emoji: "🥒", label: "cucumber" },
    { emoji: "🌶️", label: "hot_pepper" },
    { emoji: "🌽", label: "corn" },
    { emoji: "🥕", label: "carrot" },
    { emoji: "🧄", label: "garlic" },
    { emoji: "🧅", label: "onion" },
    { emoji: "🥔", label: "potato" },
    { emoji: "🍠", label: "sweet_potato" },
    { emoji: "🥐", label: "croissant" },
    { emoji: "🍞", label: "bread" },
    { emoji: "🥖", label: "baguette" },
    { emoji: "🥨", label: "pretzel" },
    { emoji: "🥯", label: "bagel" },
    { emoji: "🥞", label: "pancakes" },
    { emoji: "🧇", label: "waffle" },
    { emoji: "🧀", label: "cheese" },
    { emoji: "🍖", label: "meat" },
    { emoji: "🍗", label: "poultry_leg" },
    { emoji: "🥩", label: "steak" },
    { emoji: "🥓", label: "bacon" },
    { emoji: "🍔", label: "burger" },
    { emoji: "🍟", label: "fries" },
    { emoji: "🍕", label: "pizza" },
    { emoji: "🌭", label: "hotdog" },
    { emoji: "🥪", label: "sandwich" },
    { emoji: "🌮", label: "taco" },
    { emoji: "🌯", label: "burrito" },
    { emoji: "🥙", label: "stuffed_flatbread" },
    { emoji: "🧆", label: "falafel" },
    // ... 더 많은 음식 이모지 추가 가능
];

export const objectEmojis = [
    { emoji: "💡", label: "lightbulb" },
    { emoji: "📱", label: "smartphone" },
    { emoji: "💻", label: "laptop" },
    { emoji: "🖥️", label: "desktop" },
    { emoji: "🖨️", label: "printer" },
    { emoji: "⌨️", label: "keyboard" },
    { emoji: "🖱️", label: "mouse" },
    { emoji: "🕹️", label: "joystick" },
    { emoji: "🗜️", label: "clamp" },
    { emoji: "🧲", label: "magnet" },
    { emoji: "🧪", label: "test_tube" },
    { emoji: "🧫", label: "petri_dish" },
    { emoji: "🧬", label: "dna" },
    { emoji: "🔬", label: "microscope" },
    { emoji: "🔭", label: "telescope" },
    { emoji: "📡", label: "satellite" },
    { emoji: "💸", label: "money_with_wings" },
    { emoji: "💵", label: "dollar" },
    { emoji: "💴", label: "yen" },
    { emoji: "💶", label: "euro" },
    { emoji: "💷", label: "pound" },
    { emoji: "🪙", label: "coin" },
    { emoji: "💰", label: "moneybag" },
    { emoji: "🧧", label: "red_envelope" },
    { emoji: "💳", label: "credit_card" },
    // ... 더 많은 오브젝트 이모지 추가 가능
];

export const symbolEmojis = [
    { emoji: "❤️", label: "heart" },
    { emoji: "🧡", label: "orange_heart" },
    { emoji: "💛", label: "yellow_heart" },
    { emoji: "💚", label: "green_heart" },
    { emoji: "💙", label: "blue_heart" },
    { emoji: "💜", label: "purple_heart" },
    { emoji: "🖤", label: "black_heart" },
    { emoji: "🤍", label: "white_heart" },
    { emoji: "💔", label: "broken_heart" },
    { emoji: "❣️", label: "heart_exclamation" },
    { emoji: "💕", label: "two_hearts" },
    { emoji: "💞", label: "revolving_hearts" },
    { emoji: "💓", label: "beating_heart" },
    { emoji: "💗", label: "growing_heart" },
    { emoji: "💖", label: "sparkling_heart" },
    { emoji: "💘", label: "heart_arrow" },
    { emoji: "💝", label: "heart_ribbon" },
    { emoji: "💟", label: "heart_decor" },
    { emoji: "☮️", label: "peace" },
    { emoji: "✝️", label: "cross" },
    { emoji: "☪️", label: "star_crescent" },
    { emoji: "🕉️", label: "om" },
    { emoji: "☸️", label: "wheel_dharma" },
    { emoji: "✡️", label: "star_david" },
    { emoji: "🔯", label: "six_pointed_star" },
    { emoji: "🕎", label: "menorah" },
    { emoji: "☯️", label: "yin_yang" },
    { emoji: "☦️", label: "orthodox_cross" },
    { emoji: "🛐", label: "place_worship" },
    { emoji: "⛎", label: "ophiuchus" },
    { emoji: "♈", label: "aries" },
    { emoji: "♉", label: "taurus" },
    { emoji: "♊", label: "gemini" },
    { emoji: "♋", label: "cancer" },
    { emoji: "♌", label: "leo" },
    { emoji: "♍", label: "virgo" },
    { emoji: "♎", label: "libra" },
    { emoji: "♏", label: "scorpio" },
    { emoji: "♐", label: "sagittarius" },
    { emoji: "♑", label: "capricorn" },
    { emoji: "♒", label: "aquarius" },
    { emoji: "♓", label: "pisces" },
    { emoji: "🆔", label: "id" },
    { emoji: "⚛️", label: "atom" },
    { emoji: "🉑", label: "accept" },
    { emoji: "🌀", label: "cyclone" },
    { emoji: "♻️", label: "recycle" },
    { emoji: "⚠️", label: "warning" },
    { emoji: "🚸", label: "children_crossing" },
    { emoji: "⛔", label: "no_entry" },
    { emoji: "🚫", label: "prohibited" },
    { emoji: "🔞", label: "18" },
    { emoji: "☢️", label: "radioactive" },
    { emoji: "☣️", label: "biohazard" },
    // ... 더 많은 심볼 이모지 추가 가능
];

export const allEmojis = [
    ...peopleEmojis,
    ...animalEmojis,
    ...foodEmojis,
    ...objectEmojis,
    ...symbolEmojis,
];